common:
  godel-cache:
    key: &godel-cache-key v1-godel-cache-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}
    <<: &restore-godel-cache
      restore_cache:
        keys:
          - *godel-cache-key
    <<: &save-godel-cache
      save_cache:
        key: *godel-cache-key
        paths:
          - ~/.godel

  yarn-cache:
    key: &yarn-cache-key v1-yarn-cache-{{ checksum "yarn.lock" }}
    <<: &restore-yarn-cache
      restore_cache:
        keys:
          - *yarn-cache-key
    <<: &save-yarn-cache
      save_cache:
        key: *yarn-cache-key
        paths:
          - node_modules

  test-results:
    dir: &results-dir /tmp/test-results
    <<: &store-results
      store_test_results:
        path: *results-dir
    <<: &store-artifacts
      store_artifacts:
        path: *results-dir
        destination: test-results

### Jobs ###

version: 2
jobs:
  build:
    working_directory: /go/src/github.com/palantir/policy-bot
    environment:
      TESTS_DIR: *results-dir
    docker:
      - image: nmiyake/go:go-darwin-linux-1.11-t134
    steps:
      - checkout
      - *restore-godel-cache
      - run: ./godelw version
      - *save-godel-cache
      - run: mkdir -p "${TESTS_DIR}"
      - run: ./godelw build
      - run: ./godelw verify --apply=false --junit-output="$TESTS_DIR/$CIRCLE_PROJECT_REPONAME-tests.xml"
      - *store-results
      - *store-artifacts
      - persist_to_workspace:
          root: .
          paths:
            - build/policy-bot

  build-frontend:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - *restore-yarn-cache
      - run: yarn install
      - *save-yarn-cache
      - run: yarn run build:production
      - persist_to_workspace:
          root: .
          paths:
            - build/static

  dist:
    working_directory: /go/src/github.com/palantir/policy-bot
    docker:
      - image: nmiyake/go:go-darwin-linux-1.11-docker-17.06.0-ce-bsdtar-unzip-t134
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - *restore-godel-cache
      - run: ./godelw dist
      - run: ./godelw docker build --verbose

  publish:
    working_directory: /go/src/github.com/palantir/policy-bot
    docker:
      - image: nmiyake/go:go-darwin-linux-1.11-docker-17.06.0-ce-bsdtar-unzip-t134
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
      - run: ./godelw docker build --verbose
      - run: ./godelw docker push

### Workflows ###

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters: { tags: { only: /.*/ } }
      - build-frontend:
          filters: { tags: { only: /.*/ } }
      - dist:
          filters: { tags: { only: /.*/ } }
          requires:
            - build
            - build-frontend
      - publish:
          requires: [ dist ]
          filters:
            tags: { only: '/^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/' }
            branches: { ignore: '/.*/' }
