# Options for the http server
server:
  # The listen address and port
  address: "0.0.0.0"
  port: 8080
  # The public URL, used for URL generation when the server is behind a proxy
  # Can also be set by the POLICYBOT_PUBLIC_URL environment variable.
  public_url: http://localhost:8080
  # Uncomment the "tls_config" block to enable HTTPS support in the server.
  # The cert and key files must be usable by net/http.ListenAndServeTLS().
  # tls_config:
  #   cert_file: /path/to/server.pem
  #   key_file: /path/to/server.key

# Options for logging output
logging:
  # If true, logs are printed in human-readable form. We recommend using
  # "false" to output JSON-formatted logs in production
  # Can also be set by the POLICYBOT_LOG_PRETTY environment variable.
  text: false
  # Set a minimum logging level threshold
  # Choose from: debug, info, warn, error
  # Can also be set by the POLICYBOT_LOG_LEVEL environment variable.
  level: debug

# Options for the GitHub response cache. When the cache reaches max_size, the
# oldest entries are evicted. Size properties can use any format supported by
# https://github.com/c2h5oh/datasize
#
# cache:
#   max_size: "50MB"

# Options for webhook processing workers. Events are dropped if the queue is
# full. The defaults are shown below.
#
# workers:
#   workers: 10
#   queue_size: 100
#   github_timeout: 10s

# Options for connecting to GitHub
github:
  # The URL of the GitHub homepage. Can also be set by the GITHUB_WEB_URL
  # environment variable.
  web_url: "https://github.com"
  # The base URL for v3 (REST) API requests. Can also be set by the
  # GITHUB_V3_API_URL environment variable.
  v3_api_url: "https://api.github.com"
  # The base URL for v4 (GraphQL) API requests. Can also be set by the
  # GITHUB_V4_API_URL environment variable.
  v4_api_url: "https://api.github.com/graphql"
  app:
    # The integration ID of the GitHub app. Can also be set by the
    # GITHUB_APP_INTEGRATION_ID environment variable.
    integration_id: 1
    # A random string used to validate webhooks. Can also be set by the
    # GITHUB_APP_WEBHOOK_SECRET environment variable.
    webhook_secret: "app_secret"
    # The private key of the GitHub app. Can also be set by the
    # GITHUB_APP_PRIVATE_KEY environment variable.
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      xxxxx
      xxxxx
      xxxxx
      -----END RSA PRIVATE KEY-----
  oauth:
    # The client ID of the OAuth app associated with the GitHub app. Can also
    # be set by the GITHUB_OAUTH_CLIENT_ID environment variable.
    client_id: "client_id"
    # The client secret of the OAuth app associated with the GitHub app. Can
    # also be set by the GITHUB_OAUTH_CLIENT_SECRET environment variable.
    client_secret: "client_secret"

# Options for user sessions
sessions:
  # A random string used to sign session cookies. Can also be set by the
  # POLICYBOT_SESSIONS_KEY environment variable.
  key: "secretsessionkey"

# Options for application behavior. The defaults are shown below.
#
# options:
#   # The path to the policy file in a repository. Can also be set by the
#   # POLICYBOT_OPTIONS_POLICY_PATH environment variable.
#   policy_path: .policy.yml
#
#   # The name of an organization repository to look in for a shared policy if
#   # a repository does not define a policy file. Can also be set by the
#   # POLICYBOT_OPTIONS_SHARED_REPOSITORY environment variable.
#   shared_repository: .github
#
#   # The path to the policy file in the shared organization repository.
#   # Can also be set by the POLICYBOT_OPTIONS_SHARED_POLICY_PATH environment variable.
#   shared_policy_path: policy.yml
#
#   # The context prefix for status checks created by the bot. Can also be set by the
#   # POLICYBOT_OPTIONS_STATUS_CHECK_CONTEXT environment variable.
#   status_check_context: policy-bot

# Options for locating the frontend files. By default, the server uses appropriate
# paths for the binary distribution and Docker container. For local development,
# uncomment this section to use the alternate paths below.
#
# 'static' is the file system path to the assembled CSS and JS assets.
# 'templates' is the file system path to the Go template files.
#
# files:
#   static: build/static
#   templates: server/templates
